# Generated by Django 4.1.4 on 2022-12-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0003_alter_usergroups_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroups',
            table='guard_user_groups',
        ),
    ]
